### PR TITLE
#321 Require additional license terms when the license is custom.

### PR DESCRIPTION
**Pull request by kleintom**
Feel free to change the error string.

### CODE REVIEW

**Comment by kleintom** [comment]
This adds the 'error' class to the field_user_content_license_add textarea form element, but as far as I can tell neither bulma nor bulmabug defines that class, so the textarea doesn't change appearance at all on error for standard users. For admin, using a different theme, it does:
red
John, is that something that should be added to bulma or bulmabug, or are we just relying on error messages?

**Comment by clouseau** [comment]
Sounds like a missing feature from bulma. Bulma is the general theme; bulmabug is BugGuide-specific subtheme. For example, if a generous donor helped us set up a 10 million dollar endowment we could launch PlantGuide, which would use bulma and a PlantGuide-specific subtheme.

**Comment by kleintom** [comment]
Also need to fix this on the user registration form (user_register_form I think), currently blocked by #325. (I'll also replace 'und' with LANGUAGE_NONE...)

**Comment by kleintom** [comment]
Okay, this should be ready.

**Comment by kleintom** [comment]
Rebased.

**Pull request merged**
